//! Golden-file tests over the four fixture feeds.
//!
//! Each fixture is one complete billing period cut from the real export, flanked by two partial
//! ones, and each exists to prove a particular rule:
//!
//! | fixture | proves |
//! |---|---|
//! | `civic_holiday` | the August Civic Holiday is off-peak -- the one date where the OEB list and the ESA list disagree |
//! | `dst_fall` | a 745-interval period is complete |
//! | `dst_spring` | a 671-interval period is complete |
//! | `billed_period` | the month that reconciles against a real invoice |
//!
//! The goldens are text, not workbooks. A generated `.xlsx` is a zip and has no readable diff, and
//! the entire value of a golden file is that somebody reads the diff before committing it.
//! Regenerate with:
//!
//! ```text
//! UPDATE_GOLDEN=1 cargo test --test integration -- green_button::fixtures_golden
//! ```
//!
//! Then **read what changed**. Regenerating without reading turns these into a rubber stamp.
//!
//! `Peak_values` is dumped in full -- it is three data rows. `Interval_values` is dumped as its
//! header, its first and last few rows, its row count and its column totals: 792 rows of it would
//! be 4,700 lines nobody would read, while the totals still catch a change anywhere in the middle.
//!
//! Each cell records its value, number format, horizontal alignment and fill, and each sheet
//! records its default and explicit row heights. Alignment and row heights are here because both
//! have already been got wrong once -- the billing-period column was centred where the reference
//! workbook left-aligns it, and every row was 15pt where the reference is 13.8 -- and neither
//! showed up in a dump that recorded only values and number formats.

use super::{fixture, fixtures_dir};
use ev_cost_recovery::{
    green_button::{read_gb_feed, write_gb_workbook},
    hydro_bill::BILL_END_DAY,
};
use std::{cmp, env, fmt::Write as _, fs, path::Path, process};
use umya_spreadsheet::{Worksheet, reader};

const FIXTURES: &[&str] = &["billed_period", "civic_holiday", "dst_fall", "dst_spring"];

/// The fixture whose generated workbook is committed as the formatting standard.
///
/// `billed_period` shows every formatting state in one file: a complete 744-interval period, two
/// partial ones carrying the red fill, all four TOU columns populated, a blank demand-window group
/// on the period that is entirely off-peak, and the anomalies column.
///
/// It lives here rather than somewhere that sounds more official because it is regenerated by the
/// same `UPDATE_GOLDEN=1` run as the text goldens, so it cannot drift from the code. A committed
/// workbook that nothing regenerates goes stale and then misleads, which is worse than not having
/// one. The Python-era workbook under `docs/reference/` is the opposite case — never regenerated,
/// never read by a test, kept only as provenance.
const STANDARD: &str = "billed_period";

#[test]
fn each_fixture_matches_its_golden() {
    let update = env::var_os("UPDATE_GOLDEN").is_some();
    let mut failures = Vec::new();

    for name in FIXTURES {
        // No `{name}.XML:` prefix on the panic: `GbReadError` names the file itself, from its own
        // `path` field.
        let feed = read_gb_feed(&fixture(&format!("{name}.XML"))).unwrap_or_else(|e| panic!("{e}"));

        // A scratch directory per fixture, since tests run in parallel. A normal test run never
        // writes into tests/fixtures.
        let dir = env::temp_dir().join(format!("gb_golden_{}_{name}", process::id()));
        fs::create_dir_all(&dir).unwrap();
        let workbook = dir.join(format!("{name}.xlsx"));
        let _ = fs::remove_file(&workbook);
        write_gb_workbook(&workbook, &feed, BILL_END_DAY).unwrap();

        let actual = dump(&workbook);

        let golden = fixtures_dir().join(format!("{name}.golden.txt"));
        if update {
            fs::write(&golden, &actual).unwrap();
            if *name == STANDARD {
                let committed = fixtures_dir().join(format!("{name}.xlsx"));
                fs::copy(&workbook, &committed).unwrap();
            }
            fs::remove_dir_all(&dir).ok();
            continue;
        }
        fs::remove_dir_all(&dir).ok();
        let expected = fs::read_to_string(&golden).unwrap_or_default();
        if actual != expected {
            failures.push(name);
            eprintln!("--- {name} differs ---");
            for diff in first_differences(&expected, &actual, 12) {
                eprintln!("{diff}");
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{failures:?} differ from their goldens. Rerun with UPDATE_GOLDEN=1, then read the diff."
    );
}

/// The whole `Peak_values` sheet, then `Interval_values` in summary.
fn dump(path: &Path) -> String {
    let book = reader::xlsx::read(path).expect("the workbook just written must read back");
    let mut out = String::new();

    let peak = book
        .sheet_by_name("Peak_values")
        .expect("Peak_values sheet");
    out.push_str("== Peak_values ==\n");
    dump_geometry(&mut out, peak);
    for row in 1..=peak.highest_row() {
        dump_row(&mut out, peak, row);
    }

    let interval = book
        .sheet_by_name("Interval_values")
        .expect("Interval_values sheet");
    let last = interval.highest_row();
    writeln!(
        out,
        "\n== Interval_values ==\ndata rows: {}",
        last.saturating_sub(3)
    )
    .unwrap();
    dump_geometry(&mut out, interval);
    for row in 1..=6.min(last) {
        dump_row(&mut out, interval, row);
    }
    out.push_str("...\n");
    for row in last.saturating_sub(2)..=last {
        dump_row(&mut out, interval, row);
    }
    // Totals catch any change in the rows the excerpt skips.
    for (col, name) in [(3u32, "kwh"), (4, "kw"), (5, "kva")] {
        let total: f64 = (4..=last)
            .filter_map(|row| interval.cell((col, row)))
            .filter_map(|c| c.value().parse::<f64>().ok())
            .sum();
        writeln!(out, "total {name}: {total:.3}").unwrap();
    }
    out
}

fn dump_row(out: &mut String, sheet: &Worksheet, row: u32) {
    for col in 1..=sheet.highest_column() {
        let Some(cell) = sheet.cell((col, row)) else {
            continue;
        };
        let value = cell.value();
        let style = cell.style();
        let format = style
            .number_format()
            .map(|f| f.format_code())
            .unwrap_or_default();
        let align = style
            .alignment()
            .map(|a| format!("{:?}", a.horizontal()))
            .unwrap_or_else(|| "-".to_string());
        let fill = match style.background_color() {
            Some(c) => format!("  FILL:{:?}", c.argb()),
            None => String::new(),
        };
        if value.is_empty() && fill.is_empty() {
            continue;
        }
        writeln!(
            out,
            "{}{row}  {value}  [{format}] {align}{fill}",
            column_letters(col)
        )
        .unwrap();
    }
}

/// Default row height, and any row that overrides it. Both were wrong once and invisible to a dump
/// that recorded only cell contents.
fn dump_geometry(out: &mut String, sheet: &Worksheet) {
    writeln!(
        out,
        "default row height: {}",
        sheet.sheet_format_properties().default_row_height()
    )
    .unwrap();
    // Collapsed into runs. Interval_values sets an explicit height on all 792 data rows, and
    // listing them one by one would bury the two header rows that actually differ.
    let heights: Vec<(u32, f64)> = (1..=sheet.highest_row())
        .filter_map(|r| sheet.row_dimension(r).map(|d| (r, d.height())))
        .filter(|(_, h)| *h > 0.0)
        .collect();
    // customHeight decides whether the application may auto-fit a row. The reference leaves every
    // row auto-fitted, and a pinned row renders differently from the same stored number.
    let pinned: Vec<u32> = (1..=sheet.highest_row())
        .filter_map(|r| sheet.row_dimension(r).map(|d| (r, d.custom_height())))
        .filter(|(_, custom)| *custom)
        .map(|(r, _)| r)
        .collect();
    let mut runs: Vec<String> = Vec::new();
    let mut i = 0;
    while i < heights.len() {
        let (start, height) = heights[i];
        let mut end = start;
        while i + 1 < heights.len()
            && heights[i + 1].1 == height
            && heights[i + 1].0 == heights[i].0 + 1
        {
            i += 1;
            end = heights[i].0;
        }
        runs.push(if start == end {
            format!("{start}:{height}")
        } else {
            format!("{start}-{end}:{height}")
        });
        i += 1;
    }
    writeln!(out, "explicit row heights: {}", runs.join(" ")).unwrap();
    writeln!(out, "rows pinned (customHeight): {}", pinned.len()).unwrap();
}

/// 1 -> A, 27 -> AA.
fn column_letters(mut index: u32) -> String {
    let mut letters = String::new();
    while index > 0 {
        let rem = (index - 1) % 26;
        letters.insert(0, (b'A' + rem as u8) as char);
        index = (index - 1) / 26;
    }
    letters
}

/// The first differing lines, so a failure says what changed rather than dumping two files.
fn first_differences(expected: &str, actual: &str, limit: usize) -> Vec<String> {
    expected
        .lines()
        .zip(actual.lines())
        .enumerate()
        .filter(|(_, (e, a))| e != a)
        .take(limit)
        .map(|(i, (e, a))| format!("  line {}:\n    golden: {e}\n    actual: {a}", i + 1))
        .chain(
            match expected.lines().count().cmp(&actual.lines().count()) {
                cmp::Ordering::Equal => None,
                _ => Some(format!(
                    "  line count: golden {}, actual {}",
                    expected.lines().count(),
                    actual.lines().count()
                )),
            },
        )
        .collect()
}
