//! What the rendered reports in `tests/fixtures/sessions/` *are*, read as text.
//!
//! Nothing here renders anything. Every test below opens a committed `.report.md` and inspects it,
//! which is why they live out here rather than beside the renderer: the constraint they pin is
//! about the file that ships, not about the code that produced it. What produces those files is
//! checked in `src/session/report_rendering_tests.rs`, which can reach the estimating call
//! directly; these two halves are regenerated by the one `UPDATE_REPORT_GOLDEN` variable.
//!
//! Splitting it this way means a golden that has drifted from the renderer and a golden that has
//! stopped being legible fail as separate tests, naming separate faults.

use std::{fs, iter};

use super::fixtures_dir;

/// The stems whose rendered reports are committed.
const CASES: [&str; 2] = ["Session_Report_Diagram", "Session_Report_Anomalies"];

/// The constraint the renderer exists to satisfy: the output has to be legible with no markdown
/// renderer at all. Checked against the golden files themselves, so it holds for what ships.
#[test]
fn golden_reports_are_readable_as_plain_text() {
    for stem in CASES {
        let path = fixtures_dir().join(format!("{stem}.report.md"));
        let Ok(md) = fs::read_to_string(&path) else {
            continue; // covered by the renderer's own test
        };
        for (i, line) in md.lines().enumerate() {
            let at = format!("{stem}.report.md:{}", i + 1);
            assert!(
                !line.starts_with("    "),
                "{at}: four-space indent renders as a code block: {line:?}"
            );
            assert!(
                !line.starts_with('#'),
                "{at}: hash heading; setext underlines read better raw: {line:?}"
            );
            assert!(
                !line.contains("<br"),
                "{at}: HTML break shows literally: {line:?}"
            );
            assert!(
                line.chars().count() <= 90,
                "{at}: {} columns, too wide to read raw: {line:?}",
                line.chars().count()
            );
        }
        assert!(
            !md.contains("**"),
            "{stem}: bold markers are noise in plain text"
        );
        assert!(
            !md.contains('`'),
            "{stem}: backticks are noise in plain text"
        );
    }
}

/// Anomalies are scoped to the interval, not to the file: a session report covers a billing period
/// while a rendered report covers one window in it.
///
/// The fixture carries two sessions for this, and the golden file is where the outcome shows. A
/// spike the following day must not appear, however anomalous. A record whose reported end precedes
/// its start — the extreme of `InconsistentDuration` — sits inside the window and must appear,
/// which it only does because the overlap test normalises the span rather than taking
/// `start < hi && end > lo` at face value.
#[test]
fn anomalies_are_scoped_to_the_interval() {
    let md = fs::read_to_string(fixtures_dir().join("Session_Report_Anomalies.report.md")).unwrap();
    assert!(
        !md.contains("FARSPIKE"),
        "a session a day outside the interval was reported:\n{md}"
    );
    assert!(
        md.contains("REVERSED"),
        "a record whose end precedes its start, inside the interval, went unreported:\n{md}"
    );
}

/// `ExcessiveAvgKw` carries its figure in the table cell, while the kind itself stays a bare
/// token.
///
/// The value is written into the cell rather than onto the enum, so the workbook's `anomalies`
/// column remains a list of variant names `AnomalyKind::from_token` can read back, and the glossary
/// under the table still explains each kind once rather than once per session. `EXCESS` draws
/// 7.2 kW, above the breaker rating taken at the top of the normal voltage band.
#[test]
fn an_excessive_average_power_is_reported_with_its_figure() {
    let md = fs::read_to_string(fixtures_dir().join("Session_Report_Anomalies.report.md")).unwrap();
    assert!(
        md.contains("| ExcessiveAvgKw(7.200) |"),
        "the figure is missing from the cell:\n{md}"
    );
    // The glossary explains the kind, so it names the kind and not one session's figure.
    assert!(
        md.contains("- ExcessiveAvgKw - average kilowatts above"),
        "the glossary entry is missing or carries a figure:\n{md}"
    );
}

/// Every table in every golden file has rows of equal width. That padding is what makes the output
/// line up in a monospace font, and nothing else checks it.
#[test]
fn golden_report_tables_are_padded_evenly() {
    for stem in CASES {
        let path = fixtures_dir().join(format!("{stem}.report.md"));
        let Ok(md) = fs::read_to_string(&path) else {
            continue;
        };
        let mut block: Vec<(usize, usize)> = Vec::new();
        for (i, line) in md.lines().chain(iter::once("")).enumerate() {
            if line.starts_with('|') {
                block.push((i + 1, line.chars().count()));
            } else if !block.is_empty() {
                let w = block[0].1;
                for (ln, got) in &block {
                    assert_eq!(
                        *got, w,
                        "{stem}.report.md:{ln}: ragged table row, {got} columns against {w}"
                    );
                }
                block.clear();
            }
        }
    }
}
