//! The site-load table, pinned to a golden file, and the copy of it under `docs/` pinned to that
//! golden in turn.
//!
//! Nothing here reads a session report. [`site_load_report`] takes no input: it renders the site
//! model from the constants in `session::site_model`, and it is public API, so this is an
//! integration test in the ordinary sense — the crate is used the way a caller uses it.
//!
//! The golden is regenerated by the same variable as every other, so one command rewrites them
//! all:
//!
//! ```sh
//! UPDATE_REPORT_GOLDEN=1 cargo test
//! ```
//!
//! The documented copy is refreshed by hand, from the golden:
//!
//! ```sh
//! cp tests/fixtures/sessions/site_load.report.txt docs/session/site-load-report-marcus.txt
//! ```
//!
//! No test writes to `docs/`. A document is something a person publishes, and a test run that
//! quietly rewrites one leaves a change nobody chose in a file a reader is trusted to have read.

use ev_cost_recovery::session::site_load_report;
use std::{env, fs, path::PathBuf};

use super::fixtures_dir;
use crate::common::normalize_eol;

/// Where the documented copy lives, relative to the manifest.
///
/// Named once because two tests would otherwise spell it out, and the failure message of the
/// second one has to name it a third time.
const DOCUMENTED: &str = "docs/session/site-load-report-marcus.txt";

/// `.txt` rather than `.md`: it is fixed-width plain text with no markdown in it at all, and
/// naming it otherwise would invite someone to render it. It is the table
/// `docs/session/site-model-marcus.md` §4 is read against, so a change to
/// any electrical constant should be seen here before it is believed anywhere else.
#[test]
fn the_site_load_table_matches_its_golden_file() {
    let rendered = site_load_report();
    let golden = fixtures_dir().join("site_load.report.txt");

    if env::var_os("UPDATE_REPORT_GOLDEN").is_some() {
        fs::write(&golden, &rendered).unwrap();
        return;
    }

    let expected = fs::read_to_string(&golden).unwrap_or_else(|e| {
        panic!(
            "{}: {e}\nRun with UPDATE_REPORT_GOLDEN=1 to create it.",
            golden.display()
        )
    });
    assert_eq!(
        normalize_eol(&expected),
        normalize_eol(&rendered),
        "the site-load table differs from its golden file. Read the diff, and if the change is \
         intended regenerate with UPDATE_REPORT_GOLDEN=1."
    );
}

/// The copy under `docs/` is the same table, and is kept because end users read documentation
/// rather than fixtures.
///
/// Two copies of a rendered table drift, and this one is the user-facing half — so it is pinned
/// rather than trusted. It is checked against the golden rather than against the renderer, because
/// the test above already holds the golden to the renderer: one hop each, and between them the
/// document is what the code produces.
///
/// `#[ignore]`d because it opens `docs/`, and a release build must not. `cargo test` skips it with
/// no flag involved, so the release workflow reaches nothing under `docs/` while `ci.yml` asks for
/// it by name on every push.
#[test]
#[ignore = "reads docs/session/site-load-report-marcus.txt"]
fn the_documented_site_load_table_matches_the_golden() {
    let golden = fixtures_dir().join("site_load.report.txt");
    let documented = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(DOCUMENTED);

    let expected = fs::read_to_string(&golden).unwrap_or_else(|e| {
        panic!(
            "{}: {e}\nRun with UPDATE_REPORT_GOLDEN=1 to create it.",
            golden.display()
        )
    });
    let actual =
        fs::read_to_string(&documented).unwrap_or_else(|e| panic!("{}: {e}", documented.display()));

    assert_eq!(
        normalize_eol(&actual),
        normalize_eol(&expected),
        "{DOCUMENTED} differs from the golden it is a copy of. It is what a user is shown, so \
         refresh it with `cp tests/fixtures/sessions/site_load.report.txt {DOCUMENTED}` rather \
         than editing it."
    );
}
