//! The site-load table, pinned to a golden file.
//!
//! Nothing here reads a session report. [`site_load_report`] takes no input: it renders the site
//! model from the constants in `session::site_model`, and it is public API, so this is an
//! integration test in the ordinary sense — the crate is used the way a caller uses it.
//!
//! Regenerated by the same variable as every other golden, so one command rewrites them all:
//!
//! ```sh
//! UPDATE_REPORT_GOLDEN=1 cargo test
//! ```

use ev_cost_recovery::session::site_load_report;
use std::{env, fs};

use super::fixtures_dir;

/// `.txt` rather than `.md`: it is fixed-width plain text with no markdown in it at all, and
/// naming it otherwise would invite someone to render it. It is the table
/// `docs/session/site-model-marcus.md` §4 is read against, so a change to
/// any electrical constant should be seen here before it is believed anywhere else.
#[test]
fn the_site_load_table_matches_its_golden_file() {
    let rendered = site_load_report();
    let golden = fixtures_dir().join("site_load.report.txt");

    if env::var_os("UPDATE_REPORT_GOLDEN").is_some() {
        fs::write(&golden, &rendered).unwrap();
        return;
    }

    let expected = fs::read_to_string(&golden).unwrap_or_else(|e| {
        panic!(
            "{}: {e}\nRun with UPDATE_REPORT_GOLDEN=1 to create it.",
            golden.display()
        )
    });
    assert_eq!(
        expected, rendered,
        "the site-load table differs from its golden file. Read the diff, and if the change is \
         intended regenerate with UPDATE_REPORT_GOLDEN=1."
    );
}
